In [30]:
from tensorflow.keras.preprocessing.text import one_hot

In [31]:
### sentences
sent=[
'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

In [32]:
## define vocabulary size
voc_size= 10000

In [33]:
## one hot representation for every word
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2861, 7242, 8921, 6766],
 [2861, 7242, 8921, 8799],
 [2861, 6827, 8921, 9255],
 [796, 443, 391, 8938, 7487],
 [796, 443, 391, 8938, 5323],
 [6965, 2861, 6104, 8921, 1362],
 [7869, 9293, 8454, 8938]]

In [34]:
## word embedding representation
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential 

In [35]:
import numpy as np

In [36]:
sent_length = 8
Embedding_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(Embedding_docs)

[[   0    0    0    0 2861 7242 8921 6766]
 [   0    0    0    0 2861 7242 8921 8799]
 [   0    0    0    0 2861 6827 8921 9255]
 [   0    0    0  796  443  391 8938 7487]
 [   0    0    0  796  443  391 8938 5323]
 [   0    0    0 6965 2861 6104 8921 1362]
 [   0    0    0    0 7869 9293 8454 8938]]


In [ ]:
## feature representation
dim = 10


In [41]:
## embedding model
model = Sequential()
model.add(Embedding(input_dim=voc_size,
                    output_dim=dim,
                    input_shape=(sent_length,)))
model.compile('adam','mse')


c:\Users\uday\Desktop\simpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [42]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(Embedding_docs)
##every word gets represented by 10 dimensions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


array([[[-0.03973649, -0.04363288,  0.02114422,  0.02946894,
         -0.04653627, -0.00203516, -0.0114992 , -0.00419486,
         -0.04348072,  0.00410433],
        [-0.03973649, -0.04363288,  0.02114422,  0.02946894,
         -0.04653627, -0.00203516, -0.0114992 , -0.00419486,
         -0.04348072,  0.00410433],
        [-0.03973649, -0.04363288,  0.02114422,  0.02946894,
         -0.04653627, -0.00203516, -0.0114992 , -0.00419486,
         -0.04348072,  0.00410433],
        [-0.03973649, -0.04363288,  0.02114422,  0.02946894,
         -0.04653627, -0.00203516, -0.0114992 , -0.00419486,
         -0.04348072,  0.00410433],
        [-0.04092067, -0.00588812, -0.02972336, -0.00573383,
          0.03164579, -0.04087765,  0.03004551,  0.04773133,
         -0.03031348, -0.03969427],
        [ 0.00891384, -0.01839821,  0.00506359,  0.03580209,
         -0.02156108, -0.03720667, -0.02341929,  0.01829027,
          0.00093799,  0.03000766],
        [-0.00423769, -0.0293822 , -0.03249279,  0.0